#!/usr/bin/perl -w
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::Build::CreateLinks  qw(:all);
use File::Path;

#--------------------------------------------------
# actions for nethserver-snort-update event
#--------------------------------------------------

$event = "nethserver-snort-update";

templates2events("/etc/snort/snort.conf", $event);
templates2events("/etc/sudoers", $event);
event_services($event, 'snort' => 'restart');
event_actions($event, 'initialize-default-databases' => '00');


#--------------------------------------------------
# actions for nethserver-snort-save event
#--------------------------------------------------

$event = "nethserver-snort-save";

event_templates($event, '/etc/snort/snort.conf');
event_templates($event, '/etc/snort/pulledpork.conf');
event_services($event, 'snort' => 'reload');


